### ISSUE TITLE
Add new features to Ng for v4.1.2

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#245]
**Is your feature request related to a problem? Please describe.**

Go through change log for 4.12 in ids enterprise https://github.com/infor-design/enterprise/blob/4.12.x/docs/CHANGELOG.md

Add any new settings or make issues for the more complicated things that cannot be hit on first pass (which will be listed here)

- [x] #963 - Add new settings for message dialog
- [x] #473 - Input for clear formatting button
- [x] #889 - useCurrentTime setting #261
- [x] #378 - Added export separator option
- [x] #667 - Add ability to run code on click on empty message
- [x] #250 - Standlone Paging
