### ISSUE TITLE
Add new features to Ng for v4.1.3

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#274]
**Is your feature request related to a problem? Please describe.**

Go through change log for 4.124 in ids enterprise https://github.com/infor-design/enterprise/blob/4.14.x/docs/CHANGELOG.md

Add any new settings or make issues for the more complicated things that cannot be hit on first pass (which will be listed here)

- [x] #1088 - Added a new config option to menu button `hideMenuArrow`
- [x] #269 - Flex toolbar wrapper
- [x] #862 - Removed customVaidation setting.
- [x] #214 - Stopping renderloop
- [x] #1094 - Bar chart short, medium label support for adapting the chart to responsive views.
- [x] #1046 - Added a maxLength option to texarea
- [x] #1147 - Added a maxGrow option to texarea
- [x] #1170 - Added customColors option to the color picker
- [x] #1003 - Tree got aded sortstop and sortstart events 
- [x] #398 - Added beforeOpen to autocomplete.
- [x] #1172 - Add/confirm Promises polyfill

**Comment by tjamesallen15** [comment]
Question on 1094. The settings are add inside of the "ticks" which is already added in the angular. I don't see the need of change. Open for suggestions here. Thank you

**Comment by tmcconechy** [comment]
You can test this example out for 1094 in NG. https://github.com/infor-design/enterprise/blob/master/app/views/components/bar/example-long-text.html#L23-L25

I guess you might not need to do anything actually as the data in in the model code https://github.com/infor-design/enterprise-ng/blob/master/src/app/bar/bar.demo.ts#L20

Maybe just update that example to show the different label sizes (then resize the page like in EP to see them in action).

Thanks!

**Comment by tjamesallen15** [comment]
Thanks for the reply about 1094 @tmcconechy.

Another question is how should I apply 1172 in NG? I might be confused on what should be applied that's why I'm asking for clarification.

Thanks !

**Comment by tjamesallen15** [comment]
I have an issue also in my workspace. It doesn't contain any errors when building "ng s".

However the view cannot be displayed on the browser.

<img width="1010" alt="screen shot 2019-01-08 at 11 15 37 am" src="https://user-images.githubusercontent.com/34049950/50807853-e6a14080-1336-11e9-84e1-fb3dc16e8e8b.png">

Thanks

**Comment by tmcconechy** [comment]
Looks like your missing the ids-enterprise code or it could be the `--serve-path` change recently.
Try:

```
npm install
npm run build
npm run start
```

**Comment by tmcconechy** [comment]
For 1172 my idea was that the searchfield now uses this polyfil https://github.com/infor-design/enterprise/blob/master/package.json#L67 so i think it should be fine. Just test that searchfield still works in NG if it does there is nothing left to do. (I was thinking maybe we needed to add the reference in NG but now i do not think we do). So if searchfield tests out ok - nothing to do on that point.
