### ISSUE TITLE
Add new features to Ng for v4.14

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#304]
**Is your feature request related to a problem? Please describe.**

Go through change log for 4.124 in ids enterprise https://github.com/infor-design/enterprise/blob/4.14.x/docs/CHANGELOG.md

Add any new settings or make issues for the more complicated things that cannot be hit on first pass (which will be listed here)

- [ ] #1179 - Datepicker day of the week setting - new setting on datepicker `firstDayOfWeek` (number) -https://github.com/infor-design/enterprise/blob/master/src/components/datepicker/datepicker.js#L37
- [ ] #385 - Added caseSensitive option to autocomplete https://github.com/infor-design/enterprise/pull/1323/files#diff-5c55879abfa90c556c4a18a0a5ebf119R131
- [ ] #420 - Add headerAlign option to datagrid columns object https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L1037
