### ISSUE TITLE
Add new features to Ng for v4.15 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#334]
**Is your feature request related to a problem? Please describe.**

Go through change log for 4.15 in ids enterprise https://github.com/infor-design/enterprise/blob/4.15.x/docs/CHANGELOG.md

Add any new settings or make issues for the more complicated things that cannot be hit on first pass (which will be listed here)

- [x] #1422 - Add setting for filtered child rows to datagrid settings as per https://github.com/infor-design/enterprise/pull/1480/files#diff-7a47cbfa760f2056d4f9b91cf583d3fcR109
- [x] #653 - Add 'lookup' to the list of supported 'filterTypes' in the datagrid column option as per https://github.com/infor-design/enterprise/pull/1455/files#diff-7a47cbfa760f2056d4f9b91cf583d3fcR1220
- [x] #1303 - Add new methods to the datagrid (rowNode , cellNode  clearDirtyClass, clearDirty, clearDirtyRow, clearDirtyCell, dirtyCells) as per https://github.com/infor-design/enterprise/pull/1409/files#dff-7a47cbfa760f2056d4f9b91cf583d3fcR4623
