### ISSUE TITLE
Add new features to Ng for v4.16.0

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#370]
**Is your feature request related to a problem? Please describe.**

This will be a running list of changes that will need to be added in a future branch to match changes in 4.16.x. Will fill this in when i review the release log on beta of 4.16

- [x] #1413 - Add new boolean setting for preview mode as per https://github.com/infor-design/enterprise/pull/1637/files#diff-01545ba1faac2160d90c963e9a1d374fR36
- [x] #1181 - Add public api for setting values on filter fields https://github.com/infor-design/enterprise/pull/1617/files#diff-0cc2184007444561023799125799944aR171
- [x] #1629 - Add new hierarchy stacked API settings (Done @pwpatton ?)
- [x] #457 - Add App menu tooltip setting as per https://github.com/infor-design/enterprise/pull/1623/files#diff-75bb29fcad7b97e804de3fd00e8252d6R34
- [x] #464 - Add Frozen Column Settings as per https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L130
