### ISSUE TITLE
Add new features to Ng for v4.17.0

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#387]
**Is your feature request related to a problem? Please describe.**

This will be a running list of changes that will need to be added in a future branch to match changes in 4.17.x. 
- [x] make sure https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/locale/soho-locale.d.ts is updated
- [x] #1552 and #402 - Because of the way that languages work now will need to update this code https://github.com/infor-design/enterprise-ng/blob/master/src/app/locale-initializer/locale-initializer.service.ts#L58
- [x] #441 - Add groupSize to the locale types so that it can be viewed. Check other types like firstDayofWeek
- [x] #592 - Add new locale api for timezones event as per https://github.com/infor-design/enterprise/pull/1683/files#diff-3792f94525dff5169376546b60ecacb7R452  (setLanguage, extendTranslations, defaultLocales, defaultLocales, supportedLocales)
- [x] #1021 add beforerowactivated event https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L6669
- [x] #1699 - Add an example for compact form https://github.com/infor-design/enterprise/pull/1737

**Comment by pwpatton** [comment]
@tmcconechy  Hi Tim, can we put each in its own ticket?

**Comment by tmcconechy** [comment]
Yes we could break them out more. Just recording them for now.

**Comment by pwpatton** [comment]
ok, that sounds good. so record them for now and then a ticket for each as we go.

**Comment by tmcconechy** [comment]
yeah i think so, especially if different people take them one by one or we have a lot to add.

**Comment by pwpatton** [comment]
yea, and I think it'll be less confusing to work on, commit, and PR if each ticket is "one" thing

**Comment by bthharper** [comment]
@tmcconechy can you give me an idea what change is required in the `locale-initialiser`?  We have equivalent code in place in out applications so wanted to understand what changes are required.

**Comment by tmcconechy** [comment]
@bthharper Sure, because i seperated the language from the cultures they are in a different array now. So essentially put them in `Soho.Locale.languages[this.lang]` and use the two digit language code and not `Soho.Locale.cultures[this.locale]` with the four-digit code. To avoid problems again later i made a method you can just call to extend:

https://github.com/infor-design/enterprise/blob/master/app/views/components/locale/test-extend-messages.html#L18-L22

**Comment by tmcconechy** [comment]
Another method used is 
```
Soho.Locale.set(locale)
.done(() => {
  if (Soho.Locale.currentLocale.data.messages !== undefined) {
    data.browserMessages.forEach((message) => {
      Soho.Locale.currentLocale.data.messages[ message.messageId ] = {
        id: message.messageId,
        value: message.messageValue
      };
    });
  }
```

Should add a test for this (or what it changes to)
