### ISSUE TITLE
Add new features to Ng for v4.18.0

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#421]
**Is your feature request related to a problem? Please describe.**

This will be a running list of changes that will need to be added in a future branch to match changes in 4.18.x. 

- [x] soho-mask.directive - Add groupsize option to the mask api https://github.com/infor-design/enterprise/pull/1850/files#diff-7a3e3c219e93d6376d9c21ca82de696eR34
- [ ] ~soho-code-block - Any new api from https://github.com/infor-design/enterprise-ng/issues/355 if added~
- [x] soho-datagrid tooltip function - Add new option for datagrid tooltip feature https://github.com/infor-design/enterprise/pull/1947/files?file-filters%5B%5D=.js&file-filters%5B%5D=.md
- [ ] ~soho-flex-toolbar - Add settings for header, masthead, editor to use #471~
- [ ] ~role-switcher - Any new options for https://github.com/infor-design/enterprise/issues/1935 if needed~
- [ ] ~personalization api - Add new API for personalize to NG https://github.com/infor-design/enterprise/issues/1866 and https://github.com/infor-design/enterprise/issues/1847~
- [x] Add new settings to application menu for menu switcher: #443
- [ ] ~Update jquery to 3.4.1 for 4.19~
- [ ] Add standalone expandable area example #1935
- [ ] Add settings to use locale in mask #440
- [x] Add notification component (done in master)
- [ ] Set to patch 4.18.1 (coming soon)

**Comment by vonnyw** [comment]
Add new settings to application menu for menu switcher: https://github.com/infor-design/enterprise-ng/issues/443

**Comment by EdwardCoyle** [comment]
Specifically for the Flex Toolbar one, the settings needed aren't directly on the Flex Toolbar wrapper, but on any component that consumes it.  As of #1120 we finished:
- [ ] Header
- [ ] Masthead
- [ ] Editor
- [ ] Listbuilder (partial)

All of those components' Angular counterparts need a `useFlexToolbar` setting.  If any of them construct the toolbar markup internally, they also need to be retrofitted to alternatively build Flex Toolbar markup when this setting is `true`.

**Comment by tmcconechy** [comment]
Closing this as we will push the rest to next version see https://github.com/infor-design/enterprise-ng/issues/472
