### ISSUE TITLE
Add new features to Ng for v4.19.0 and 4.20

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#472]
**Is your feature request related to a problem? Please describe.**

This will be a running list of changes that will need to be added in a future branch to match changes in 4.19.x and remained from 4.18.x. Each will have a separate ticket linked. Issues with a separate ticket are scribbled out.

4.18
- [x] ~soho-code-block - Any new api from https://github.com/infor-design/enterprise-ng/issues/355 if added~
- [x] ~soho-flex-toolbar - Add settings for header, masthead, editor to use #471~
- [x] ~role-switcher - Any new options for https://github.com/infor-design/enterprise/issues/1935 if needed~
- [x] ~personalization api - Add new API for personalize to NG https://github.com/infor-design/enterprise/issues/1866 and https://github.com/infor-design/enterprise/issues/1847~
- [x] Update jquery to 3.4.1
- [x] Allow specifying a fill color for svg of soho-button="icon", soho-icon #440 
- [x] Add standalone expandable area example #1935
- [x] Add isRowDisabled setting for http://localhost:4000/components/datagrid/example-disabled-rows.html

4.19
- [x] Summary form features https://github.com/infor-design/enterprise/issues/1765
- [x] Add new settings from https://github.com/infor-design/enterprise/issues/1906
- [x] New functions from https://github.com/infor-design/enterprise/issues/2091
- [x] Any new settings here https://github.com/infor-design/enterprise/issues/1909
- [x] Add beforecommitcelledit from https://github.com/infor-design/enterprise/pull/1965

4.20 (So far)
- [ ] Add widget notification example https://github.com/infor-design/enterprise/issues/1881
- [ ] Datepicker / year picker redesisgn form features https://github.com/infor-design/enterprise/issues/1958
- [ ] Compact form features https://github.com/infor-design/enterprise/issues/1955
- [ ] Add new settings from https://github.com/infor-design/enterprise/issues/1818

**Comment by tmcconechy** [comment]
Suggest we make this issue as 4.19 features only. Since the 4.20 is just to be released the features for that will trail into a 5.6. So we can do those later and i'll make a new issue for that with a list of details based on the release change log.
