### ISSUE TITLE
Add new Settings for 4.20 and 4.21

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise-ng#555]
**Is your feature request related to a problem? Please describe.**
For the new things in 4.20 want to add as much as we can to 5.5 NG

**List of items**
- [x] Add meta options from #2446 https://github.com/infor-design/enterprise/pull/2608/files#diff-22d84c71524b1b9addb8568d1f0d468eR426
- [x] Add new locale option from https://github.com/infor-design/enterprise/issues/2637
- [x] Add new locale option as per #2640 
- [x] Add locale and NG 8 to the quick start
- [x] Add stretchOnChange setting as per #2174 https://github.com/infor-design/enterprise/pull/2284/files#diff-7a47cbfa760f2056d4f9b91cf583d3fcR74
- [x] Ensure placeholder option is on the columns as per https://github.com/infor-design/enterprise/pull/2409/files#diff-5fbda2ff2db65447672d20512f259279R69
- [x] Ensure min and max width or an datagrid as per https://github.com/infor-design/enterprise/pull/2378/files#diff-d33438081f706f2faaf9d221dc29ace4R29
- [x] Ensure beforeCommitCellEdit is on the column defs as per https://github.com/infor-design/enterprise/pull/2464/files#diff-c3ca4c5e46c1ac35ac953a0b3bc00176R102
- [x] Ensure datepicker types are updated as per https://github.com/infor-design/enterprise/pull/2531/files#diff-d39862bd4f9fdae4b1ff67f89b890752R57
- [x] Update form compact as per https://github.com/infor-design/enterprise/issues/2193 with new fields
- [x] Update filter types on autocomplete https://github.com/infor-design/enterprise/pull/2388/files#diff-746bd03df9aa0b2f37f91480573f0ccbR10
- [x] Add new types to calendar events https://github.com/infor-design/enterprise/pull/2457/files#diff-6f5415db8b0a3a55acf6bc23fc075dceR738
- [x] Update calendar update types https://github.com/infor-design/enterprise/issues/2419
- [x] Add event information to callbacks https://github.com/infor-design/enterprise/issues/2419
- [x] Change types on the column dynamic tooltip function https://github.com/infor-design/enterprise/issues/2333
- [x] Remove advanceMonths https://github.com/infor-design/enterprise/issues/970
- [x] Add new pager settings https://github.com/infor-design/enterprise/issues/2356
- [x] Add fixedRowHeight setting https://github.com/infor-design/enterprise/pull/2690
- [x] Add new locale option https://github.com/infor-design/enterprise/pull/2685/files#diff-3792f94525dff5169376546b60ecacb7R260

**Done**
- [x] Make commitCellEdit public in NG
- [x] Add toast draggable setting
